#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_TOTAL_BOIDS 		10
#define DEFAULT_WINDOW_HEIGHT		720
#define DEFAULT_WINDOW_WIDTH		1280
#define DEFUALT_NUM_THREADS			4
#define DEFAULT_BOID_SIZE			4
#define DEFAULT_TURN_SPEED			0.5
#define DEFAULT_VISUAL_RANGE		100
#define DEFAULT_PERSONAL_SPACE		20
#define DEFAULT_COHERENCE_WT 		0.75
#define DEFAULT_SEPERARATION_WT		0.75
#define DEFAULT_ALIGNMENT_WT		0.75
#define DEFAULT_MAX_SPEED			6
#define DEFAULT_MIN_SPEED			2
#define DEFAULT_TOP_MARGIN			50
#define DEFAULT_BOT_MARGIN			50
#define DEFAULT_LFT_MARGIN			50
#define DEFAULT_RGT_MARGIN			50

